// Mock data — plausible shapes, sourced from telemetry/report schemas in the
// real codebase (Attractor Observatory/project_telemetry/, reports/, motifs/).
// Numbers are illustrative; nothing here is claim-bearing.

window.MOCK = {
  health: {
    score: 87,
    band: "verified",
    components: [
      { name: "determinism",      score: 0.96, status: "verified"    },
      { name: "calibration",      score: 0.91, status: "verified"    },
      { name: "provenance",       score: 0.99, status: "verified"    },
      { name: "detector_agreement", score: 0.83, status: "verified"  },
      { name: "coverage",         score: 0.74, status: "warning"     },
      { name: "storage",          score: 0.92, status: "verified"    },
      { name: "claim_hygiene",    score: 0.95, status: "verified"    },
      { name: "builder_calibration", score: 0.88, status: "verified" },
      { name: "doctrine_compliance", score: 1.00, status: "verified" },
    ],
  },
  branch: {
    name: "feature/control-room-v0",
    aheadOfMain: 14,
    dirty: false,
    lastCommit: { sha: "d3f2a1c", msg: "TASK-CB-007 · pulse deck wiring", author: "codex", agoMin: 14 },
  },
  tests: { passed: 208, failed: 0, knownFailuresExcluded: 4, runtimeMs: 41200 },
  currentTask: { id: "TASK-CB-008", name: "world observatory · density grid", estimatedH: 4.0, elapsedH: 2.7, deltaForecast: 0.92 },
  recentEvents: [
    { t: "12s",  kind: "active",   text: "world chamber W3 rerendered (field, ~2.1s)" },
    { t: "3m",   kind: "verified", text: "208 pytests passing on feature/control-room-v0" },
    { t: "14m",  kind: "verified", text: "commit d3f2a1c · TASK-CB-007 closed (Δ 0.89)" },
    { t: "1h",   kind: "warning",  text: "C014 BFG · gate G3 amber (review)" },
    { t: "2h",   kind: "failed",   text: "FALSIFIER · floor_connectivity point-attractor verdict" },
    { t: "4h",   kind: "active",   text: "codex_audit_002 catch · D22 violation queued" },
    { t: "1d",   kind: "verified", text: "C013 ratified · 35/35 substance gates" },
    { t: "2d",   kind: "warning",  text: "K7 calibration drift +0.04 (within band)" },
  ],
  campaigns: [
    { id: "C002", title: "observatory spine",          status: "verified",  date: "2026-01-09", gates: [1,1,1,2,1,1] },
    { id: "C003", title: "world reconstruction · W3+", status: "verified",  date: "2026-01-22", gates: [1,1,1,1,1,2] },
    { id: "C004", title: "K-corpus expansion",         status: "verified",  date: "2026-02-03", gates: [1,1,2,1,1,1] },
    { id: "C005", title: "null factory N=1000",        status: "verified",  date: "2026-02-18", gates: [1,1,1,1,1,1] },
    { id: "C006", title: "detector triangulation",     status: "verified",  date: "2026-03-02", gates: [1,1,1,2,1,1] },
    { id: "C007", title: "substance audit (D17.5)",    status: "verified",  date: "2026-03-16", gates: [1,2,1,1,1,1] },
    { id: "C008", title: "strict substance floors",    status: "verified",  date: "2026-03-29", gates: [1,1,3,1,2,1] },
    { id: "C009", title: "BFG basin-floor geometry",   status: "active",    date: "2026-04-12", gates: [1,2,0,0,0,0] },
    { id: "C010", title: "floor candidate replication",status: "verified",  date: "2026-04-18", gates: [1,1,1,1,1,1] },
    { id: "C011", title: "lens registry expansion",    status: "verified",  date: "2026-04-22", gates: [1,1,1,1,1,1] },
    { id: "C012", title: "biology shadow rebuild",     status: "warning",   date: "2026-04-25", gates: [1,1,2,2,2,1] },
    { id: "C013", title: "BFG-PR confound (CB-002)",   status: "verified",  date: "2026-04-26", gates: [1,1,1,1,1,1] },
    { id: "C014", title: "floor_connectivity falsified", status: "failed",  date: "2026-04-29", gates: [1,1,3,1,1,3] },
  ], // 0=missing, 1=verified, 2=warning, 3=failed
  worlds: [
    { id: "W1",  name: "CRN",              family: "chemistry",     density: "claim_ready_densified",   traces: 142, motifs: 6, falsifiers: 0, kappa: 0.83, hue: "--world-chemistry"     },
    { id: "W2",  name: "Protocell",        family: "chemistry",     density: "claim_ready_densified",   traces: 118, motifs: 5, falsifiers: 1, kappa: 0.71, hue: "--world-protocell"     },
    { id: "W3",  name: "Field",            family: "chemistry",     density: "exploratory_densified",   traces: 96,  motifs: 4, falsifiers: 0, kappa: 0.62, hue: "--world-field"         },
    { id: "W4",  name: "Morphogenesis",    family: "biology",       density: "exploratory_densified",   traces: 72,  motifs: 4, falsifiers: 0, kappa: 0.58, hue: "--world-morphogenesis" },
    { id: "W5",  name: "Digital",          family: "digital",       density: "exploratory_densified",   traces: 88,  motifs: 5, falsifiers: 0, kappa: 0.66, hue: "--world-digital"       },
    { id: "W6",  name: "Ecosystem",        family: "biology",       density: "trace_valid_sparse",      traces: 41,  motifs: 2, falsifiers: 0, kappa: 0.34, hue: "--world-ecosystem"     },
    { id: "W7",  name: "Swarm",            family: "biology",       density: "trace_valid_sparse",      traces: 38,  motifs: 2, falsifiers: 0, kappa: 0.21, hue: "--world-swarm"         },
    { id: "W8",  name: "Cognitive",        family: "cognitive",     density: "skeleton",                traces: 12,  motifs: 1, falsifiers: 0, kappa: null, hue: "--world-cognitive"     },
    { id: "W9",  name: "Origins-mineral",  family: "chemistry",     density: "skeleton",                traces: 10,  motifs: 1, falsifiers: 0, kappa: null, hue: "--world-origins"       },
    { id: "W10", name: "Hypergraph",       family: "multiscale",    density: "skeleton",                traces: 7,   motifs: 0, falsifiers: 0, kappa: null, hue: "--world-hypergraph"    },
    { id: "W11", name: "Quasispecies",     family: "digital",       density: "skeleton",                traces: 5,   motifs: 0, falsifiers: 0, kappa: null, hue: "--world-quasispecies"  },
    { id: "W12", name: "Symbiogenesis",    family: "biology",       density: "skeleton",                traces: 4,   motifs: 0, falsifiers: 0, kappa: null, hue: "--world-symbiogenesis" },
    { id: "W13", name: "Multiscale",       family: "multiscale",    density: "trace_valid_sparse",      traces: 22,  motifs: 1, falsifiers: 1, kappa: 0.42, hue: "--world-multiscale"    },
  ],
  motifs: [
    { id: "closure",       status: "verified",    floor: "broad",     worlds: ["W1","W2","W3","W5"] },
    { id: "boundary",      status: "verified",    floor: "broad",     worlds: ["W2","W4","W7"] },
    { id: "repair",        status: "verified",    floor: "rugged",    worlds: ["W2","W6","W12"] },
    { id: "memory",        status: "warning",     floor: "candidate", worlds: ["W5","W8"] },
    { id: "coordination",  status: "warning",     floor: "candidate", worlds: ["W7","W6"] },
    { id: "gradient",      status: "verified",    floor: "broad",     worlds: ["W3","W4"] },
    { id: "floor_connectivity", status: "failed", floor: "point",     worlds: ["W13"] },
  ],
  falsifiers: [
    { id: "F-014-1", t: "2026-04-29", motif: "floor_connectivity", verdict: "point-attractor",   campaign: "C014", severity: "high",   downgrade: "C010 → falsified" },
    { id: "F-013-2", t: "2026-04-26", motif: "memory",             verdict: "null > signal",     campaign: "C013", severity: "medium", downgrade: "C012 → exploratory" },
    { id: "F-008-7", t: "2026-03-29", motif: "boundary",           verdict: "engineered floor",  campaign: "C008", severity: "high",   downgrade: "softened-floors → strict" },
  ],
  doctrines: [
    { id: "D7",  title: "No toys",                          mode: "binding", failure: "11/13 worlds were 60-80 line stubs", campaign: "C002", hash: "a1b2c3d" },
    { id: "D8",  title: "No number-generator corpora",      mode: "binding", failure: "K5-K10 were `for i in range(24): scenario['signal']=...`", campaign: "C002", hash: "b2c3d4e" },
    { id: "D9",  title: "No engineered pass criteria",      mode: "binding", failure: "lens predictions hand-tuned to pass band", campaign: "C002", hash: "c3d4e5f" },
    { id: "D10", title: "No hardcoded science",             mode: "binding", failure: "biology/shadow.py used Python set literal", campaign: "C002", hash: "d4e5f6a" },
    { id: "D11", title: "Truth pass before new claims",     mode: "binding", failure: "C002-006 published on contaminated foundation", campaign: "C006", hash: "e5f6a7b" },
    { id: "D12", title: "Gates are measurements, not counts",mode: "binding",failure: "68 trivial counts as 'gates'", campaign: "C006", hash: "f6a7b8c" },
    { id: "D13", title: "Substance budgets stay honest",    mode: "binding", failure: "scope_delta + estimation_delta diverging", campaign: "C007", hash: "a7b8c9d" },
    { id: "D14", title: "No scenario-internal hardcoding",  mode: "binding", failure: "W4 stamped segmentation answer onto cells", campaign: "C007", hash: "b8c9dae" },
    { id: "D15", title: "No engineered floor",              mode: "binding", failure: "anticipated for C009 BFG calibration", campaign: "C009", hash: "c9daebf" },
    { id: "D16", title: "Implementation-diversity is multi-scale", mode: "binding", failure: "scalar diversity is tunable", campaign: "C009", hash: "daebfa0" },
    { id: "D17", title: "Floor falsifiers are publishable", mode: "binding", failure: "point-attractor verdict on motif", campaign: "C014", hash: "ebfa0b1" },
    { id: "D18", title: "Equivalence basis content-locked", mode: "binding", failure: "post-hoc basis movement (Codex catch)", campaign: "C009", hash: "fa0b1c2" },
    { id: "D19", title: "Source-bound extraction (intake)", mode: "binding", failure: "biology ingestion needs provenance lock", campaign: "factory", hash: "0b1c2d3" },
    { id: "D20", title: "Quarantine candidate registries",  mode: "binding", failure: "factory entries cannot promote without audit", campaign: "factory", hash: "1c2d3e4" },
    { id: "D21", title: "No promotion without signed audit",mode: "binding", failure: "audit chain must be cryptographic", campaign: "factory", hash: "2d3e4f5" },
    { id: "D22", title: "Empty rooms beat stocked rooms",   mode: "binding", failure: "Class 12 (Decorative Completeness) candidate", campaign: "control_room", hash: "3e4f5a6" },
    { id: "D23?",title: "(candidate) Cross-architecture audit", mode: "candidate", failure: "Codex-Builder agreement gap", campaign: "—", hash: "—" },
  ],
  builderTasks: [
    { i: 1,  est: 0.5, act: 5.2 }, { i: 2,  est: 1.0, act: 8.0 },
    { i: 3,  est: 2.0, act: 7.4 }, { i: 4,  est: 3.0, act: 9.8 },
    { i: 5,  est: 2.0, act: 5.2 }, { i: 6,  est: 4.0, act: 7.6 },
    { i: 7,  est: 3.0, act: 4.4 }, { i: 8,  est: 4.0, act: 4.7 },
    { i: 9,  est: 3.5, act: 4.0 }, { i: 10, est: 4.0, act: 4.3 },
    { i: 11, est: 3.0, act: 3.4 }, { i: 12, est: 3.5, act: 3.7 },
    { i: 13, est: 4.0, act: 4.2 }, { i: 14, est: 4.0, act: 4.0 },
    { i: 15, est: 3.5, act: 3.6 }, { i: 16, est: 4.5, act: 4.6 },
    { i: 17, est: 3.0, act: 3.0 }, { i: 18, est: 4.0, act: 4.1 },
    { i: 19, est: 3.5, act: 3.5 },
  ],
};
